"""Add Comment model

Revision ID: 786fcdaff5cd
Revises: 937502be882e
Create Date: 2026-07-23 12:16:30.270517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786fcdaff5cd'
down_revision = '937502be882e'
branch_labels = None
depends_on = None


def upgrade():
    # Hand-written from the start this time, not autogenerated: same
    # create_all()-races-a-new-table situation documented on the `ratings`
    # migration (937502be882e) and in PROJECT_STATUS.md -- create_all()
    # always creates a brand-new table before Alembic compares schemas
    # (autogenerate saw no diff here either), and on a fresh environment
    # migrate.upgrade() runs right after create_all() on every startup, so
    # an unconditional CREATE TABLE would fail with "already exists" and
    # silently stall alembic_version forever. The existence check makes
    # this idempotent regardless of which of the two created the table
    # first.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "comments" in inspector.get_table_names():
        return

    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    op.drop_table("comments")
