"""Add Rating model

Revision ID: 937502be882e
Revises: c43d354413b9
Create Date: 2026-07-23 11:51:35.295795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937502be882e'
down_revision = 'c43d354413b9'
branch_labels = None
depends_on = None


def upgrade():
    # Hand-written, not autogenerated: `flask db migrate` runs through the
    # app factory, which runs db.create_all() on every invocation -- for a
    # brand-new table like this one, that silently created `ratings` before
    # Alembic ever compared schemas, so autogenerate saw no diff and
    # produced an empty migration.
    #
    # The existence check below exists for the same reason, and matters
    # beyond just local dev: create_all() and migrate.upgrade() both run on
    # *every* app startup (see app/__init__.py), in that order. On a fresh
    # environment (e.g. the first production deploy after this migration
    # ships), create_all() will always create this brand-new table first,
    # so an unconditional CREATE TABLE here would fail with "already
    # exists" -- and since that failure is caught by the startup try/except
    # (logged, not raised), alembic_version would silently never advance
    # past this revision, permanently breaking every startup and blocking
    # any migration chained after this one. Checking first makes this
    # migration idempotent, matching the same defensive pattern
    # db.create_all() itself already uses.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "ratings" in inspector.get_table_names():
        return

    op.create_table(
        "ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("stars >= 1 AND stars <= 5", name="ck_rating_stars_range"),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "resource_id", name="uq_rating_user_resource"),
    )


def downgrade():
    op.drop_table("ratings")
