"""Drop University.location; add case-insensitive unique index on Course(university_id, name)

Revision ID: a79e6c917800
Revises: 
Create Date: 2026-07-23 10:51:13.607947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79e6c917800'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###

    # Hand-added: autogenerate can't detect expression-based indexes under
    # SQLite (see models.py Course.__table_args__), so this is written
    # manually. Plain CREATE/DROP INDEX with a lower(name) expression works
    # identically on both SQLite and Postgres, unlike op.create_index()
    # with a sa.text() column, which some SQLite/Alembic combinations mangle
    # inside batch mode.
    op.execute(
        "CREATE UNIQUE INDEX uq_course_university_name_ci "
        "ON courses (university_id, lower(name))"
    )


def downgrade():
    op.execute("DROP INDEX uq_course_university_name_ci")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
